#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/../.." && pwd)"

OUTDIR="${1:-${REPO_ROOT}/out_bench/fh_online_q_finetune}"
OFFLINE_OUTDIR="${OFFLINE_OUTDIR:-${OUTDIR}/offline_qloss}"
FINETUNE_OUTDIR="${FINETUNE_OUTDIR:-${OUTDIR}/online_finetuned}"
OFFLINE_CHECKPOINT_ROOT="${OFFLINE_CHECKPOINT_ROOT:-${OFFLINE_OUTDIR}/models}"
FINETUNE_CHECKPOINT_ROOT="${FINETUNE_CHECKPOINT_ROOT:-${FINETUNE_OUTDIR}/models}"

# Stage 2 is intentionally controlled separately from the offline qloss stage.
# The offline stage delegates to run_fh_offline_qloss_ladder.sh, so
# its defaults remain the current repo qloss defaults unless the OFFLINE_QLOSS_*
# variables below are explicitly changed.
OFFLINE_QLOSS_FIXED_RATIO="${OFFLINE_QLOSS_FIXED_RATIO:-1.8}"
OFFLINE_QLOSS_NM="${OFFLINE_QLOSS_NM:-6}"
OFFLINE_QLOSS_HIDDEN_WIDTH="${OFFLINE_QLOSS_HIDDEN_WIDTH:-128}"
OFFLINE_QLOSS_RES_BLOCKS="${OFFLINE_QLOSS_RES_BLOCKS:-2}"
OFFLINE_QLOSS_EPOCHS="${OFFLINE_QLOSS_EPOCHS:-300}"
OFFLINE_QLOSS_LR="${OFFLINE_QLOSS_LR:-1e-3}"
OFFLINE_QLOSS_GRAD_CLIP="${OFFLINE_QLOSS_GRAD_CLIP:-1.0}"
OFFLINE_QLOSS_BATCH_SIZE="${OFFLINE_QLOSS_BATCH_SIZE:-0}"
OFFLINE_QLOSS_STEPS_PER_EPOCH="${OFFLINE_QLOSS_STEPS_PER_EPOCH:-0}"
OFFLINE_QLOSS_TEACHER_DT="${OFFLINE_QLOSS_TEACHER_DT:-0.01}"
OFFLINE_QLOSS_LINEAR_T="${OFFLINE_QLOSS_LINEAR_T:-10.0}"
OFFLINE_QLOSS_NONLINEAR_T="${OFFLINE_QLOSS_NONLINEAR_T:-10.0}"

ONLINE_FINETUNE_EPOCHS="${ONLINE_FINETUNE_EPOCHS:-300}"
ONLINE_FINETUNE_LR="${ONLINE_FINETUNE_LR:-3e-4}"
ONLINE_FINETUNE_GRAD_CLIP="${ONLINE_FINETUNE_GRAD_CLIP:-0.25}"
ONLINE_FINETUNE_STEPS_PER_EPOCH="${ONLINE_FINETUNE_STEPS_PER_EPOCH:-5}"
ONLINE_FINETUNE_CASE_BATCH_SIZE="${ONLINE_FINETUNE_CASE_BATCH_SIZE:-1}"
ONLINE_FINETUNE_ROLLOUT_HORIZON="${ONLINE_FINETUNE_ROLLOUT_HORIZON:-256}"
ONLINE_FINETUNE_ROLLOUT_ANCHOR_SAMPLES="${ONLINE_FINETUNE_ROLLOUT_ANCHOR_SAMPLES:-1}"
ONLINE_FINETUNE_ROLLOUT_DIRECTION="${ONLINE_FINETUNE_ROLLOUT_DIRECTION:-forward}"
ONLINE_FINETUNE_TEACHER_DT="${ONLINE_FINETUNE_TEACHER_DT:-0.01}"
ONLINE_FINETUNE_LINEAR_T="${ONLINE_FINETUNE_LINEAR_T:-${TRAIN_LINEAR_T:-10.0}}"
ONLINE_FINETUNE_NONLINEAR_T="${ONLINE_FINETUNE_NONLINEAR_T:-${TRAIN_NONLINEAR_T:-10.0}}"

mkdir -p "${OUTDIR}"

echo "[closure-bidir-finetune] [1/2] Training/evaluating offline fixed-ratio qloss base models"
CHECKPOINT_ROOT="${OFFLINE_CHECKPOINT_ROOT}" \
TRAIN_FIXED_RATIO="${OFFLINE_QLOSS_FIXED_RATIO}" \
TRAIN_NM="${OFFLINE_QLOSS_NM}" \
TRAIN_HIDDEN_WIDTH="${OFFLINE_QLOSS_HIDDEN_WIDTH}" \
TRAIN_RES_BLOCKS="${OFFLINE_QLOSS_RES_BLOCKS}" \
TRAIN_EPOCHS="${OFFLINE_QLOSS_EPOCHS}" \
TRAIN_LR="${OFFLINE_QLOSS_LR}" \
TRAIN_GRAD_CLIP="${OFFLINE_QLOSS_GRAD_CLIP}" \
TRAIN_BATCH_SIZE="${OFFLINE_QLOSS_BATCH_SIZE}" \
TRAIN_STEPS_PER_EPOCH="${OFFLINE_QLOSS_STEPS_PER_EPOCH}" \
TRAIN_TEACHER_DT="${OFFLINE_QLOSS_TEACHER_DT}" \
TRAIN_LINEAR_T="${OFFLINE_QLOSS_LINEAR_T}" \
TRAIN_NONLINEAR_T="${OFFLINE_QLOSS_NONLINEAR_T}" \
TRAIN_OBJECTIVE="q_only" \
TRAIN_CONTEXT_MODE="none" \
  "${SCRIPT_DIR}/run_fh_offline_qloss_ladder.sh" "${OFFLINE_OUTDIR}"

echo "[closure-bidir-finetune] [2/2] Fine-tuning/evaluating online closure-bidir models from offline qloss checkpoints"
CHECKPOINT_ROOT="${FINETUNE_CHECKPOINT_ROOT}" \
INIT_CHECKPOINT_ROOT="${OFFLINE_CHECKPOINT_ROOT}" \
TRAIN_ONLINE_LOSS_BACKEND="fourier_hermite_closure_bidir" \
TRAIN_NV_LADDER_MODE="fixed_ratio" \
TRAIN_FIXED_RATIO="${OFFLINE_QLOSS_FIXED_RATIO}" \
TRAIN_NM="${OFFLINE_QLOSS_NM}" \
TRAIN_HIDDEN_WIDTH="${OFFLINE_QLOSS_HIDDEN_WIDTH}" \
TRAIN_RES_BLOCKS="${OFFLINE_QLOSS_RES_BLOCKS}" \
TRAIN_EPOCHS="${ONLINE_FINETUNE_EPOCHS}" \
TRAIN_LR="${ONLINE_FINETUNE_LR}" \
TRAIN_GRAD_CLIP="${ONLINE_FINETUNE_GRAD_CLIP}" \
TRAIN_STEPS_PER_EPOCH="${ONLINE_FINETUNE_STEPS_PER_EPOCH}" \
TRAIN_ONLINE_CASE_BATCH_SIZE="${ONLINE_FINETUNE_CASE_BATCH_SIZE}" \
TRAIN_ROLLOUT_HORIZON="${ONLINE_FINETUNE_ROLLOUT_HORIZON}" \
TRAIN_ROLLOUT_ANCHOR_SAMPLES="${ONLINE_FINETUNE_ROLLOUT_ANCHOR_SAMPLES}" \
TRAIN_ROLLOUT_DIRECTION="${ONLINE_FINETUNE_ROLLOUT_DIRECTION}" \
TRAIN_TEACHER_DT="${ONLINE_FINETUNE_TEACHER_DT}" \
TRAIN_LINEAR_T="${ONLINE_FINETUNE_LINEAR_T}" \
TRAIN_NONLINEAR_T="${ONLINE_FINETUNE_NONLINEAR_T}" \
  "${SCRIPT_DIR}/run_nv_sweep_online_rollout.sh" "${FINETUNE_OUTDIR}"

for artifact in summary.json nv_sweep_metric1.png nv_sweep_metric2.png fig10_learned_vs_nonlocal_nv_sweep_phase_space.png nv_sweep_phase_space_payload.npz; do
  if [[ -f "${FINETUNE_OUTDIR}/${artifact}" && "${FINETUNE_OUTDIR}/${artifact}" != "${OUTDIR}/${artifact}" ]]; then
    cp -f "${FINETUNE_OUTDIR}/${artifact}" "${OUTDIR}/${artifact}"
  fi
done

cat <<EOF

Done.

Artifacts:
  offline qloss checkpoints:       ${OFFLINE_CHECKPOINT_ROOT}
  offline qloss metrics/figures:   ${OFFLINE_OUTDIR}
  online finetuned checkpoints:    ${FINETUNE_CHECKPOINT_ROOT}
  online finetuned metrics/figures:${FINETUNE_OUTDIR}
  top-level finetuned metric 1:     ${OUTDIR}/nv_sweep_metric1.png
  top-level finetuned metric 2:     ${OUTDIR}/nv_sweep_metric2.png
  top-level finetuned phase space:  ${OUTDIR}/fig10_learned_vs_nonlocal_nv_sweep_phase_space.png
  Metric 2/Fig.10 layout:           HR reference | truncation (q=0) | learned closure

Fine-tune defaults:
  backend:         fourier_hermite_closure_bidir
  ladder mode:     fixed_ratio
  epochs:          ${ONLINE_FINETUNE_EPOCHS}
  lr:              ${ONLINE_FINETUNE_LR}
  grad clip:       ${ONLINE_FINETUNE_GRAD_CLIP}
  steps/epoch:     ${ONLINE_FINETUNE_STEPS_PER_EPOCH}
  case batch:      ${ONLINE_FINETUNE_CASE_BATCH_SIZE}
  rollout horizon: ${ONLINE_FINETUNE_ROLLOUT_HORIZON}
  anchors:         ${ONLINE_FINETUNE_ROLLOUT_ANCHOR_SAMPLES}
  direction:       ${ONLINE_FINETUNE_ROLLOUT_DIRECTION}
  train teacher dt:${ONLINE_FINETUNE_TEACHER_DT}
  linear T:        ${ONLINE_FINETUNE_LINEAR_T}
  nonlinear T:     ${ONLINE_FINETUNE_NONLINEAR_T}
EOF
