#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/../.." && pwd)"

OUTDIR="${1:-${REPO_ROOT}/out_bench/nv_sweep_online_rollout_projected_xv_H256_A1}"
PROJECTED_XV_TAIL_WINDOW="${TRAIN_PROJECTED_XV_TAIL_WINDOW:-0}"

TRAIN_ONLINE_LOSS_BACKEND="fourier_hermite_projected_xv_bidir" \
TRAIN_NV_LADDER_MODE="${TRAIN_NV_LADDER_MODE:-fixed_ratio}" \
TRAIN_TEACHER_DT="${TRAIN_TEACHER_DT:-0.01}" \
TRAIN_LINEAR_T="${TRAIN_LINEAR_T:-10.0}" \
TRAIN_NONLINEAR_T="${TRAIN_NONLINEAR_T:-10.0}" \
TRAIN_ROLLOUT_HORIZON="${TRAIN_ROLLOUT_HORIZON:-256}" \
TRAIN_ROLLOUT_ANCHOR_SAMPLES="${TRAIN_ROLLOUT_ANCHOR_SAMPLES:-1}" \
TRAIN_ROLLOUT_DIRECTION="${TRAIN_ROLLOUT_DIRECTION:-forward}" \
TRAIN_PROJECTED_XV_TAIL_WINDOW="${PROJECTED_XV_TAIL_WINDOW}" \
TRAIN_STEPS_PER_EPOCH="${TRAIN_STEPS_PER_EPOCH:-5}" \
  "${SCRIPT_DIR}/run_nv_sweep_online_rollout.sh" "${OUTDIR}"
