#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/../.." && pwd)"

OUTDIR="${1:-${REPO_ROOT}/out_bench/fh_online_projected_xv_rollout_H256_T60_target_only}"
PROJECTED_XV_TAIL_WINDOW="${TRAIN_PROJECTED_XV_TAIL_WINDOW:-0}"
PROJECTED_XV_METRIC="${TRAIN_PROJECTED_XV_METRIC:-gram_riesz}"

TRAIN_ONLINE_LOSS_BACKEND="fourier_hermite_projected_xv_bidir" \
T_FINAL="${T_FINAL:-60.0}" \
SNAPSHOT_TIMES="${SNAPSHOT_TIMES:-20.0,40.0,60.0}" \
TEACHER_DT="${TEACHER_DT:-0.01}" \
TRAIN_NV_LADDER_MODE="${TRAIN_NV_LADDER_MODE:-target_only}" \
TRAIN_FIXED_RATIO="${TRAIN_FIXED_RATIO:-1.8}" \
TRAIN_TEACHER_DT="${TRAIN_TEACHER_DT:-0.01}" \
TRAIN_LINEAR_T="${TRAIN_LINEAR_T:-60.0}" \
TRAIN_NONLINEAR_T="${TRAIN_NONLINEAR_T:-60.0}" \
TRAIN_ROLLOUT_HORIZON="${TRAIN_ROLLOUT_HORIZON:-256}" \
TRAIN_ROLLOUT_ANCHOR_SAMPLES="${TRAIN_ROLLOUT_ANCHOR_SAMPLES:-1}" \
TRAIN_ROLLOUT_ANCHOR_POOL_SIZE="${TRAIN_ROLLOUT_ANCHOR_POOL_SIZE:-1}" \
TRAIN_ROLLOUT_DIRECTION="${TRAIN_ROLLOUT_DIRECTION:-forward}" \
TRAIN_PROJECTED_XV_TAIL_WINDOW="${PROJECTED_XV_TAIL_WINDOW}" \
TRAIN_PROJECTED_XV_METRIC="${PROJECTED_XV_METRIC}" \
TRAIN_NM="${TRAIN_NM:-6}" \
TRAIN_HIDDEN_WIDTH="${TRAIN_HIDDEN_WIDTH:-128}" \
TRAIN_RES_BLOCKS="${TRAIN_RES_BLOCKS:-2}" \
TRAIN_EPOCHS="${TRAIN_EPOCHS:-300}" \
TRAIN_LR="${TRAIN_LR:-1e-3}" \
TRAIN_GRAD_CLIP="${TRAIN_GRAD_CLIP:-1.0}" \
TRAIN_STEPS_PER_EPOCH="${TRAIN_STEPS_PER_EPOCH:-5}" \
TRAIN_ONLINE_CASE_BATCH_SIZE="${TRAIN_ONLINE_CASE_BATCH_SIZE:-1}" \
  "${SCRIPT_DIR}/run_nv_sweep_online_rollout.sh" "${OUTDIR}"
