"""Metric 2: time-integrated self-generated electric-field error.

This module compares the electric field generated by the reduced solver with the
learned closure, denoted ``E^theta``, against the high-resolution reference field
``E^HR``.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, Tuple

import numpy as np

_SQRT_FLOAT64_MAX = float(np.sqrt(np.finfo(np.float64).max))


@dataclass(frozen=True)
class FieldErrorConfig:
    """Configuration for the self-generated field error metric."""

    final_time: Optional[float] = None
    num_low_modes: Optional[int] = None
    k_max: Optional[float] = None
    mode_tol: float = 1e-12
    denom_floor: float = 1e-30
    assume_rfft_half_spectrum: bool = True
    rfft_last_mode_unique: bool = True

    def __post_init__(self) -> None:
        if self.final_time is not None and float(self.final_time) <= 0.0:
            raise ValueError("final_time must be positive")
        if self.num_low_modes is not None and int(self.num_low_modes) <= 0:
            raise ValueError("num_low_modes must be positive")
        if self.k_max is not None and float(self.k_max) <= 0.0:
            raise ValueError("k_max must be positive")
        if float(self.mode_tol) < 0.0:
            raise ValueError("mode_tol must be nonnegative")
        if float(self.denom_floor) <= 0.0:
            raise ValueError("denom_floor must be positive")


@dataclass(frozen=True)
class FieldErrorResult:
    """Result for Metric 2."""

    epsilon_E: float
    T: float
    numerator: float
    denominator: float
    num_modes: int
    selected_k: np.ndarray


@dataclass(frozen=True)
class FourierFieldComparison:
    """Aligned Fourier-space field histories used by Metric 2 and its plots."""

    times: np.ndarray
    E_hat_theta: np.ndarray
    E_hat_hr: np.ndarray
    selected_k: np.ndarray


def _validate_times_1d(times: np.ndarray) -> np.ndarray:
    times = np.asarray(times, dtype=np.float64).reshape(-1)
    if times.size < 2:
        raise ValueError("At least two time samples are required")
    if not np.all(np.isfinite(times)):
        raise ValueError("times must be finite")
    if not np.all(np.diff(times) > 0.0):
        raise ValueError("times must be strictly increasing")
    return times


def _validate_history(history: np.ndarray, n_times: int, *, complex_ok: bool) -> np.ndarray:
    arr = np.asarray(history)
    if arr.ndim != 2:
        raise ValueError(f"history must have shape (Nt, Nq), got {arr.shape}")
    if arr.shape[0] != n_times:
        raise ValueError(f"history first axis must match times length {n_times}, got {arr.shape[0]}")
    if complex_ok:
        return arr.astype(np.complex128)
    if np.iscomplexobj(arr):
        raise ValueError("physical-space field histories must be real-valued")
    return arr.astype(np.float64)


def _interp_history(
    source_times: np.ndarray,
    source_values: np.ndarray,
    target_times: np.ndarray,
) -> np.ndarray:
    source_times = np.asarray(source_times, dtype=np.float64)
    target_times = np.asarray(target_times, dtype=np.float64)
    source_values = np.asarray(source_values)
    out = np.empty((target_times.size, source_values.shape[1]), dtype=source_values.dtype)
    if np.iscomplexobj(source_values):
        for j in range(source_values.shape[1]):
            out[:, j] = np.interp(target_times, source_times, np.real(source_values[:, j])) + 1j * np.interp(
                target_times,
                source_times,
                np.imag(source_values[:, j]),
            )
        return out.astype(np.complex128)

    for j in range(source_values.shape[1]):
        out[:, j] = np.interp(target_times, source_times, source_values[:, j])
    return out.astype(np.float64)


def _shared_final_time(
    times_theta: np.ndarray,
    times_hr: np.ndarray,
    final_time: Optional[float],
) -> float:
    t_max = min(float(times_theta[-1]), float(times_hr[-1]))
    if final_time is not None:
        t_max = min(t_max, float(final_time))
    if t_max <= max(float(times_theta[0]), float(times_hr[0])):
        raise ValueError("No overlapping comparison interval is available")
    return t_max


def _comparison_times(times_hr: np.ndarray, final_time: float) -> np.ndarray:
    mask = (times_hr >= float(times_hr[0])) & (times_hr <= float(final_time))
    used = times_hr[mask]
    if used.size < 2:
        raise ValueError("Need at least two reference time samples in the comparison window")
    return used


def _weighted_modulus_sq_sum(values: np.ndarray, weights: np.ndarray) -> np.ndarray:
    values = np.asarray(values)
    weights = np.asarray(weights, dtype=np.float64)
    mag = np.abs(values)
    invalid = ~np.isfinite(mag)
    overflow = mag > _SQRT_FLOAT64_MAX
    safe_mag = np.where(invalid | overflow, 0.0, mag)
    sq_sum = np.sum(weights * safe_mag * safe_mag, axis=1, dtype=np.float64)
    bad_rows = np.any(invalid | overflow, axis=1)
    return np.where(bad_rows, np.inf, sq_sum).astype(np.float64)


class SelfGeneratedFieldErrorMetric:
    """Metric 2: time-integrated relative electric-field error."""

    def __init__(self, config: FieldErrorConfig = FieldErrorConfig()) -> None:
        self.config = config

    def _select_common_nonzero_modes(
        self,
        k_theta: np.ndarray,
        k_hr: np.ndarray,
    ) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        k_theta = np.asarray(k_theta, dtype=np.float64).reshape(-1)
        k_hr = np.asarray(k_hr, dtype=np.float64).reshape(-1)
        theta_indices = []
        hr_indices = []
        selected_k = []

        for hr_idx, kval in enumerate(k_hr):
            if abs(float(kval)) <= float(self.config.mode_tol):
                continue
            if self.config.k_max is not None and float(kval) > float(self.config.k_max):
                continue
            matches = np.flatnonzero(np.isclose(k_theta, kval, atol=self.config.mode_tol, rtol=0.0))
            if matches.size == 0:
                continue
            theta_indices.append(int(matches[0]))
            hr_indices.append(int(hr_idx))
            selected_k.append(float(kval))

        if self.config.num_low_modes is not None:
            limit = int(self.config.num_low_modes)
            theta_indices = theta_indices[:limit]
            hr_indices = hr_indices[:limit]
            selected_k = selected_k[:limit]

        if not selected_k:
            raise ValueError("No common nonzero Fourier modes were found")

        return (
            np.asarray(theta_indices, dtype=np.int64),
            np.asarray(hr_indices, dtype=np.int64),
            np.asarray(selected_k, dtype=np.float64),
        )

    def _mode_weights(self, indices: np.ndarray, nk_total: int) -> np.ndarray:
        if not bool(self.config.assume_rfft_half_spectrum):
            return np.ones((indices.size,), dtype=np.float64)

        weights = np.full((indices.size,), 2.0, dtype=np.float64)
        if bool(self.config.rfft_last_mode_unique) and nk_total >= 2:
            weights[indices == (nk_total - 1)] = 1.0
        return weights

    def prepare_fourier_comparison(
        self,
        times_theta: np.ndarray,
        E_hat_theta: np.ndarray,
        k_theta: np.ndarray,
        times_hr: np.ndarray,
        E_hat_hr: np.ndarray,
        k_hr: np.ndarray,
        *,
        final_time: Optional[float] = None,
    ) -> FourierFieldComparison:
        """Align learned and HR Fourier-space field histories on the HR time grid."""

        times_theta = _validate_times_1d(times_theta)
        times_hr = _validate_times_1d(times_hr)
        E_hat_theta = _validate_history(E_hat_theta, times_theta.size, complex_ok=True)
        E_hat_hr = _validate_history(E_hat_hr, times_hr.size, complex_ok=True)

        theta_mode_idx, hr_mode_idx, selected_k = self._select_common_nonzero_modes(k_theta, k_hr)
        T = _shared_final_time(
            times_theta,
            times_hr,
            self.config.final_time if final_time is None else final_time,
        )
        times_eval = _comparison_times(times_hr, T)
        hr_rows = np.searchsorted(times_hr, times_eval)
        theta_interp = _interp_history(times_theta, E_hat_theta[:, theta_mode_idx], times_eval)
        hr_eval = E_hat_hr[hr_rows, :][:, hr_mode_idx]
        return FourierFieldComparison(
            times=np.asarray(times_eval, dtype=np.float64),
            E_hat_theta=np.asarray(theta_interp, dtype=np.complex128),
            E_hat_hr=np.asarray(hr_eval, dtype=np.complex128),
            selected_k=np.asarray(selected_k, dtype=np.float64),
        )

    def evaluate_fourier(
        self,
        times_theta: np.ndarray,
        E_hat_theta: np.ndarray,
        k_theta: np.ndarray,
        times_hr: np.ndarray,
        E_hat_hr: np.ndarray,
        k_hr: np.ndarray,
        *,
        final_time: Optional[float] = None,
    ) -> FieldErrorResult:
        """Evaluate Metric 2 from Fourier-space electric-field histories."""

        comparison = self.prepare_fourier_comparison(
            times_theta,
            E_hat_theta,
            k_theta,
            times_hr,
            E_hat_hr,
            k_hr,
            final_time=final_time,
        )
        _, hr_mode_idx, _ = self._select_common_nonzero_modes(k_theta, k_hr)
        nk_total = _validate_history(E_hat_hr, _validate_times_1d(times_hr).size, complex_ok=True).shape[1]
        weights = self._mode_weights(hr_mode_idx, nk_total)[None, :]
        diff_sq = _weighted_modulus_sq_sum(comparison.E_hat_theta - comparison.E_hat_hr, weights)
        ref_sq = _weighted_modulus_sq_sum(comparison.E_hat_hr, weights)

        numerator = float(np.trapezoid(diff_sq, x=comparison.times))
        denominator = float(np.trapezoid(ref_sq, x=comparison.times))
        if not np.isfinite(numerator):
            epsilon_E = np.inf
        else:
            finite_denom = denominator if np.isfinite(denominator) else 0.0
            epsilon_E = np.sqrt(numerator / max(finite_denom, float(self.config.denom_floor)))
        return FieldErrorResult(
            epsilon_E=float(epsilon_E),
            T=float(comparison.times[-1]),
            numerator=numerator,
            denominator=denominator,
            num_modes=int(comparison.selected_k.size),
            selected_k=comparison.selected_k,
        )

    def evaluate_physical(
        self,
        times_theta: np.ndarray,
        E_theta: np.ndarray,
        x_theta: np.ndarray,
        times_hr: np.ndarray,
        E_hr: np.ndarray,
        x_hr: np.ndarray,
        *,
        final_time: Optional[float] = None,
    ) -> FieldErrorResult:
        """Evaluate Metric 2 directly from same-grid physical-space field histories."""

        times_theta = _validate_times_1d(times_theta)
        times_hr = _validate_times_1d(times_hr)
        E_theta = _validate_history(E_theta, times_theta.size, complex_ok=False)
        E_hr = _validate_history(E_hr, times_hr.size, complex_ok=False)
        x_theta = np.asarray(x_theta, dtype=np.float64).reshape(-1)
        x_hr = np.asarray(x_hr, dtype=np.float64).reshape(-1)

        if x_theta.shape != x_hr.shape or not np.allclose(x_theta, x_hr, rtol=0.0, atol=1e-12):
            raise ValueError("evaluate_physical requires matching x grids")
        if x_hr.size < 2:
            raise ValueError("x grid must contain at least two points")
        dx = float(x_hr[1] - x_hr[0])
        if not np.allclose(np.diff(x_hr), dx, rtol=0.0, atol=1e-12):
            raise ValueError("x grid must be uniform")

        T = _shared_final_time(
            times_theta,
            times_hr,
            self.config.final_time if final_time is None else final_time,
        )
        times_eval = _comparison_times(times_hr, T)
        theta_interp = _interp_history(times_theta, E_theta, times_eval)
        hr_eval = E_hr[np.searchsorted(times_hr, times_eval), :]

        diff_sq = float(dx) * np.sum((theta_interp - hr_eval) ** 2, axis=1)
        ref_sq = float(dx) * np.sum(hr_eval ** 2, axis=1)
        numerator = float(np.trapezoid(diff_sq, x=times_eval))
        denominator = float(np.trapezoid(ref_sq, x=times_eval))
        epsilon_E = np.sqrt(numerator / max(denominator, float(self.config.denom_floor)))
        return FieldErrorResult(
            epsilon_E=float(epsilon_E),
            T=float(times_eval[-1]),
            numerator=numerator,
            denominator=denominator,
            num_modes=0,
            selected_k=np.zeros((0,), dtype=np.float64),
        )
